
CREATE TABLE IF NOT EXISTS post(
id SERIAL NOT NULL,
time TIMESTAMP NOT NULL,
author_id INT NOT NULL,
tittle TEXT NOT NULL,
post_text TEXT NOT NULL,
is_blocked BOOLEAN NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(author_id) REFERENCES person(id) ON DELETE RESTRICT
);