CREATE TYPE status_type as ENUM ('REQUEST', 'FRIEND', 'BLOCKED', 'DECLINED', 'SUBSCRIBED');

CREATE TABLE IF NOT EXISTS friendship_status
(
	id SERIAL NOT NULL,
	time TIMESTAMP NOT NULL,
	name TEXT NOT NULL,
	code status_type,
	PRIMARY KEY(id)
);