CREATE TYPE user_type as ENUM ('MODERATOR', 'ADMIN');

CREATE TABLE users
(
	id SERIAL PRIMARY KEY  NOT NULL,
	name CHARACTER VARYING(255)  NOT NULL,
	e_mail CHARACTER VARYING(255)  NOT NULL,
	password CHARACTER VARYING(255)  NOT NULL,
	type user_type

);